version: '3.7'

services:
  slacklinegroups:
    image: syntaf/slacklinegroups_test:latest

  nginx:
    image: syntaf/slacklinegroups-nginx_test:latest

  sidekiq:
    image: syntaf/slacklinegroups_test:latest