version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: slg
      POSTGRES_PASSWORD: dev
    ports:
      - '5432:5432'
    volumes:
      - slacklinegroups-postgres:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - slacklinegroups-redis:/var/lib/redis/data

  slacklinegroups:
    build:
      context: slacklinegroups/.
      dockerfile: Dockerfile.development
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    depends_on:
      - postgres
    volumes:
      - type: bind
        source: ./slacklinegroups
        target: /opt/app/slacklinegroups
      - /opt/app/slacklinegroups/tmp
    ports:
      - '3000:3000'
    env_file:
      - .env

  sidekiq:
    build:
      context: slacklinegroups/.
      dockerfile: Dockerfile.development
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    command: bundle exec sidekiq
    depends_on:
      - postgres
      - redis
    volumes:
      - type: bind
        source: ./slacklinegroups
        target: /opt/app/slacklinegroups
      - /opt/app/slacklinegroups/tmp
    env_file:
      - .env

  webpacker:
    build:
      context: slacklinegroups/.
      dockerfile: Dockerfile.development
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
    volumes:
      - type: bind
        source: ./slacklinegroups
        target: /opt/app/slacklinegroups
      - /opt/app/slacklinegroups/tmp
    command: bin/webpack-dev-server
    env_file:
      - .env
    ports:
      - 3035:3035

volumes:
  slacklinegroups-postgres:
  slacklinegroups-redis: