version: '3.7'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: slg
      POSTGRES_PASSWORD: dev
    ports:
      - '5432:5432'

  redis:
    image: redis
    ports:
      - '6379:6379'

  slacklinegroups:
    image: syntaf/slacklinegroups_test:latest 
    depends_on:
      - postgres
      - redis
    env_file:
      - .env