apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "slacklinegroups.fullname" . }}
  labels:
    {{- include "slacklinegroups.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "slacklinegroups.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "slacklinegroups.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "slacklinegroups.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-rails-master-key
                  key: key
            - name: REDIS_URL
              value: redis://slacklinegroups-redis-master:6379/0
            - name: JOB_WORKER_URL
              value: redis://slacklinegroups-redis-master:6379/0
            - name: RAILS_SERVE_STATIC_FILES
              value: "true"
            - name: SLACKLINEGROUPS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgresql-password
            - name: SLACKLINEGROUPS_DATABASE_HOST
              value: {{ .Release.Name }}-postgresql
            - name: SENDGRID_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-sendgrid
                  key: password
            - name: SENDGRID_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-sendgrid
                  key: domain
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
