apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-sendgrid
type: Opaque
data:
    password: {{ .Values.sendgrid.password | b64enc }}
    domain: {{ .Values.sendgrid.domain | b64enc }}