include:
  - ./**/*.rb
exclude:
  - vendor/**/*
  - test/**/*
  - spec/**/*
  - examples/**/*
require:
  - actioncable
  - actionmailer
  - actionpack
  - actionview
  - activejob
  - activemodel
  - activerecord
  - activestorage
  - activesupport
reporters:
  - rubocop